version: '3'
services:
  master:
    build:
      context: .
      dockerfile: Dockerfile.master
    ports:
      - "5000:5000"

  secondary-a:
    build:
      context: .
      dockerfile: Dockerfile.secondary
    ports:
      - "5001:5001"
    # environment:
    #   - FAILURE=True
    #   - DELAY_IN_MS=1000
    depends_on:
      - master
  secondary-b:
    build:
      context: .
      dockerfile: Dockerfile.secondary
    ports:
      - "5002:5001"
    depends_on:
      - master
